INSERT INTO `utm_data` (`source`, `medium`, `campaign`, `content`, `term`) VALUES
('google', 'cpc', 'summer', 'banner', 'video'),
('google', 'cpc', 'winter', 'delta',  NULL),
('yandex', 'cpc', 'spring', 'promo',  'search'),
('yandex', 'cpc', 'spring', 'promo',  'brand'),
('yandex', 'organic', 'fall', NULL,   NULL),
('bing',   'cpc', 'black_friday', 'sidebar', 'mobile'),
('bing',   'cpc', 'black_friday', 'sidebar', 'desktop'),
('bing',   'organic', 'new_year',  NULL,     NULL),
('facebook', 'social', 'retargeting', 'feed',   'video'),
('facebook', 'social', 'retargeting', 'stories', NULL),
('facebook', 'email',  'newsletter',  NULL,      NULL),
('vk',     'social', 'spring_sale', 'wall',   'image'),
('vk',     'social', 'spring_sale', 'wall',   'text'),
('vk',     'cpc',    'remarket',    'banner',  NULL),
('twitter','social', 'brand',       NULL,      NULL),
('linkedin','b2b',   'enterprise',  'inmails', 'decision'),
('linkedin','b2b',   'enterprise',  'inmails', 'influencer'),
('linkedin','organic','thought_leadership', NULL, NULL),
('tiktok', 'video',  'awareness',   'reel',    'youth'),
('pinterest','social','inspiration', 'pin',    NULL);
